name: View app version

on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        description: App to be deployed
        type: choice
        options:
          - dps-email-poller
          - dps-email-worker
          - dps-notification-service
          - dps-payment-service
          - dps-validation-service
          - figaro-validation-service
          - spd-notification-worker
          - vips-notification-worker
      environment:
        required: true
        description: What is the targeted environment?
        type: choice
        options:
          - dev
          - test
          - prod          

jobs:
  get-app-version:
    name: Get the app-version from the POM file
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    outputs:
       app-version: ${{ steps.step1.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Project Version
        id: step1
        working-directory: "./src"
        run: |
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -P${{ github.event.inputs.app_name }})
          echo "version=$_version " >> "$GITHUB_OUTPUT"
          echo $_version

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: get-app-version
    steps:
      - name: print version     
        run: echo "${{needs.get-app-version.outputs.app-version}}"   
   


