name: View app version

on:
  workflow_dispatch: {}

jobs:
  get-app-version:
    name: Get the app-version from the POM file
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."

    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "java_version:      17"
          echo "working_directory: src/dps-email-poller"
          echo "current_directory: ${{ github.workspace }}"     
            
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          working-directory: "."

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: list - list BOM file
        run: |
          cd src/libs/dps-bom
          cat pom.xml      

      - name: CD - Get Java Project Version
        run: |
          cd src
          cd dps-email-poller
          ls -lstra
          cat pom.xml
          _version=0.5.0
          echo $_version   
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: CD - Get Java Project Version
        run: |
          cd src
          cd dps-email-poller
          ls -lstra
          cat pom.xml
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $_version             

      - name: WD - Java Project Version
        if: always()
        working-directory: "./src/dps-email-poller"
        run: |
          ls -lstra
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $_version  
