name: View app version

on:
  workflow_dispatch: {}

jobs:
  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: "src/dps-email-poller"
      java_version: 17
